### ISSUE TITLE
[feature] 컴포넌트 구현 #1

### ISSUE THREAD

**Issue by Jaminggu** [HomeChefHub/refooding-fe#1]
> 💁‍♂️ GUIDE
> 1. 집중하기 위해 작은 단위로 진행하기
> 2. 하나의 이슈에 반영되는 PR 당 코드의 변경은 300줄이 넘어가지 않도록 노력하기

## 📝 Description
컴포넌트 구현

## ✅ TODO
- [x] header
- [x] search input
- [x] go back header
- [x] button
- [x] bottom tab bar
- [x] profile image
- [x] add button
- [x] text field (게시물 작성에서 사용)
- [x] 이미지 업로드 박스
- [x] dropdown 커스턴

## 💡 ETC
작업을 진행하면서 발생한 문제나 고려해야 할 기타 사항을 작성해주세요.
