### ISSUE TITLE
[refactor] 홈화면 - 백엔드 API 변경에 따른 코드 수정 및 무한 스크롤 기능 구현 #14

### ISSUE THREAD

**Issue by Jaminggu** [HomeChefHub/refooding-fe#14]
> 💁‍♂️ GUIDE
> 1. 집중하기 위해 작은 단위로 진행하기
> 2. 하나의 이슈에 반영되는 PR 당 코드의 변경은 300줄이 넘어가지 않도록 노력하기

## 📝 Description
홈화면 백엔드 API에 맞춰 코드 수정 및 무한 스크롤 기능 구현

## ✅ TODO
- [x] 검색 레시피 구현 및 무한스크롤
- [x] 추천 레시피 코드 변경 및 무한스크롤
- [x] 찜한 레시피 코드 변경 및 무한스크롤

## 💡 ETC
작업을 진행하면서 발생한 문제나 고려해야 할 기타 사항을 작성해주세요.
