### ISSUE TITLE
[refactor] 식재료 교환 - 백엔드 API 변경에 따른 코드 수정 #15

### ISSUE THREAD

**Issue by Jaminggu** [HomeChefHub/refooding-fe#15]
> 💁‍♂️ GUIDE
> 1. 집중하기 위해 작은 단위로 진행하기
> 2. 하나의 이슈에 반영되는 PR 당 코드의 변경은 300줄이 넘어가지 않도록 노력하기

## 📝 Description
식재료 교환 화면들 코드 수정

## ✅ TODO
- [x] 검색 기능 구현
- [x] 상세화면 이미지 표시
- [x] 이미지 업로드 기능 구현

## 💡 ETC
작업을 진행하면서 발생한 문제나 고려해야 할 기타 사항을 작성해주세요.
