### ISSUE TITLE
[feature] 홈 메인화면 구현 #2

### ISSUE THREAD

**Issue by Jaminggu** [HomeChefHub/refooding-fe#2]
> 💁‍♂️ GUIDE
> 1. 집중하기 위해 작은 단위로 진행하기
> 2. 하나의 이슈에 반영되는 PR 당 코드의 변경은 300줄이 넘어가지 않도록 노력하기

## 📝 Description
홈화면 UI 구현 및 레시피 상세페이지 구현

## ✅ TODO
- [x] 화면 UI 구현
- [x] 레시피 추천 데이터 받아오기
- [x] 요리명 또는 재료명 입력으로 필터링
- [x] 하트로 찜한 레시피 구현
- [x] 로그인 전에는 랜덤 레시피

## 💡 ETC
작업을 진행하면서 발생한 문제나 고려해야 할 기타 사항을 작성해주세요.
