### ISSUE TITLE
[feature] 내 냉장고 메인화면 구현 #3

### ISSUE THREAD

**Issue by Jaminggu** [HomeChefHub/refooding-fe#3]
> 💁‍♂️ GUIDE
> 1. 집중하기 위해 작은 단위로 진행하기
> 2. 하나의 이슈에 반영되는 PR 당 코드의 변경은 300줄이 넘어가지 않도록 노력하기

## 📝 Description
진행할 작업의 설명을 작성하세요.

## ✅ TODO
- [x] 화면 UI 구현
- [x] 추가 버튼 누르면 추가 화면
- [x] 재료 추가 화면 구성
- [x] 네비게이션 설정
- [x] 삭제기능
- [x] 수정 누르면 수정화면으로

## 💡 ETC
작업을 진행하면서 발생한 문제나 고려해야 할 기타 사항을 작성해주세요.
