### ISSUE TITLE
[feature] 식재료 교환 게시판 메인화면 구현 #4

### ISSUE THREAD

**Issue by Jaminggu** [HomeChefHub/refooding-fe#4]
> 💁‍♂️ GUIDE
> 1. 집중하기 위해 작은 단위로 진행하기
> 2. 하나의 이슈에 반영되는 PR 당 코드의 변경은 300줄이 넘어가지 않도록 노력하기

## 📝 Description
진행할 작업의 설명을 작성하세요.

## ✅ TODO
- [x] 화면 UI 구현
- [x] 검색으로 필터링 기능 구현
- [x] 추가 버튼 누르면 게시판 글 쓰기 화면으로 넘어감
- [x] 서버에서 데이터 받아오기
- [x] 상세화면 navigator로 연결하기
- [x] 무한 스크롤
- [x] 이미지 썸네일

## 💡 ETC
작업을 진행하면서 발생한 문제나 고려해야 할 기타 사항을 작성해주세요.
