### ISSUE TITLE
[feature] 채팅 메인화면 구현 #5

### ISSUE THREAD

**Issue by Jaminggu** [HomeChefHub/refooding-fe#5]
> 💁‍♂️ GUIDE
> 1. 집중하기 위해 작은 단위로 진행하기
> 2. 하나의 이슈에 반영되는 PR 당 코드의 변경은 300줄이 넘어가지 않도록 노력하기

## 📝 Description
채팅 메인화면 구현입니다.

## ✅ TODO
- [x] 화면 UI 구현
- [ ] 채팅 받아오고 띄우기
- [ ] 채팅 목록 누르면 해당 채팅방으로 이동

## 💡 ETC
작업을 진행하면서 발생한 문제나 고려해야 할 기타 사항을 작성해주세요.
