### ISSUE TITLE
[feature] 마이페이지 메인화면 구현 #6

### ISSUE THREAD

**Issue by Jaminggu** [HomeChefHub/refooding-fe#6]
> 💁‍♂️ GUIDE
> 1. 집중하기 위해 작은 단위로 진행하기
> 2. 하나의 이슈에 반영되는 PR 당 코드의 변경은 300줄이 넘어가지 않도록 노력하기

## 📝 Description
진행할 작업의 설명을 작성하세요.

## ✅ TODO
- [x] 화면 UI 구현
- [ ] 프로필 수정 버튼 누르면 수정 화면으로 이동
- [ ] 공지사항, 약관 및 정책, 회원탈퇴 리스트 누르면 각각의 화면으로 이동
- [ ] 로그아웃 기능 구현

## 💡 ETC
작업을 진행하면서 발생한 문제나 고려해야 할 기타 사항을 작성해주세요.
