### ISSUE TITLE
[feature] 홈화면 - 레시피 상세화면 구현 #9

### ISSUE THREAD

**Issue by Jaminggu** [HomeChefHub/refooding-fe#9]
> 💁‍♂️ GUIDE
> 1. 집중하기 위해 작은 단위로 진행하기
> 2. 하나의 이슈에 반영되는 PR 당 코드의 변경은 300줄이 넘어가지 않도록 노력하기

## 📝 Description
레시피 상세화면 구현하기

## ✅ TODO
- [x] 화면 UI 구현
- [x] 데이터 서버에서 받아오기
- [x] RecipeCard랑 navigator로 연결
- [x] 찜하기 기능 구현

## 💡 ETC
작업을 진행하면서 발생한 문제나 고려해야 할 기타 사항을 작성해주세요.
